token = "xxx"  
channelId = 'ur channel id lol'
serverId = 'ur server id lol'

rollCommand= 'wa'
desiredKakeras = ['kakeraP','kakeraY','kakeraO','kakeraR','kakeraW','kakeraL']
desiredSeries = []
desiredCharacters = [
  'Zero Two',
  'Hatsune Miku',
  'Rem',
  'Rias Gremory',
  'Megumin',
  'Saber',
  'Mai Sakurajima',
  'Nami',
  'Power',
  'Satoru Gojo',
  'Asuna',
  'Albedo',
  '2B',
  'Makima',
  'Mikasa Ackerman',
  'Nezuko Kamado',
  'Nico Robin',
  'Miku Nakano',
  'Emilia',
  'Violet Evergarden',
  'Hange Zoë',
  'Shinobu Kochou',
  'Aqua',
  'Akame',
  'Marin Kitagawa',
  'Monkey D. Luffy',
  'Ram',
  'Nino Nakano',
  'Rin Tohsaka',
  'Yumeko Jabami',
  'Esdeath',
  'Himiko Toga',
  'Akeno Himejima',
  'Kaguya Shinomiya',
  'Yor Forger',
  'Chika Fujiwara',
  'Frieren',
  'Roronoa Zoro',
  'Kurumi Tokisaki',
  'Rei Ayanami',
  'Asuka Langley Souryuu',
  'Nobara Kugisaki',
  'Hinata Hyuuga',
  'Erza Scarlet',
  'Mitsuri Kanroji',
  'Bongo Cat',
  'Komi Shouko',
  'Levi',
  'Sukuna',
  'Maki Zenin',
  'Gawr Gura',
  'Boa Hancock',
  'Darkness',
  'Shiro',
  'Ai Hayasaka',
  'Reze',
  'C.C.',
  'Tohru',
  'Sinon',
  'Neferpitou',
  'Kurisu Makise',
  'Raphtalia',
  'Yuji Itadori',
  'Ochako Uraraka',
  'Eren Jaeger',
  'Rikka Takanashi',
  'Sanji',
  'Chiaki Nanami',
  'Nyan Cat',
  'Itsuki Nakano',
  'Tatsumaki',
  'Misa Amane',
  'Killua Zoldyck',
  'Lucy Heartfilia',
  'Ryuuko Matoi',
  'Yotsuba Nakano',
  'Kanna Kamui',
  'Mirko',
  'Joker',
  'Yoruichi Shihōin',
  'Rukia Kuchiki',
  'Venom',
  'Jolyne Cujoh',
  'Son Goku',
  'Lucy',
  'Fubuki',
  'Nagatoro-san',
  'Naruto Uzumaki',
  'Crona',
  'Kyouko Hori',
  'Denji',
  'Ken Kaneki',
  'Touka Kirishima',
  'Artoria Pendragon (Alter)',
  'Katsuki Bakugou',
  'Misato Katsuragi',
  'Annie Leonhart',
  'Toji Fushiguro',
  'Osamu Dazai'
];
pokeRoll = True
repeatMinute = '25'
